### ISSUE TITLE
Провести тест-кейс TST001

### ISSUE THREAD

**Issue by AndrewKhukhrianskyi** [AndrewKhukhrianskyi/Python-online-QA-Automation#4]

**Comment by VladosikJoskii** [comment]
https://docs.google.com/document/d/1bar_XKE1Y3dwdIxb2CTGkqoeNRRplbioc3Ysd0Cgpt8/edit?usp=sharing

**Comment by AndrewKhukhrianskyi** [comment]
Составлен тест-кейс. Ссылка выше
